/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author USER
 */
public class frmMain extends javax.swing.JFrame {

    /** Creates new form frmMain */
    public frmMain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTapTin = new javax.swing.JMenu();
        mnuThoat = new javax.swing.JMenuItem();
        mnuDanhMuc = new javax.swing.JMenu();
        mnuChatLieu = new javax.swing.JMenuItem();
        mnuNhanVien = new javax.swing.JMenuItem();
        mnuKhachHang = new javax.swing.JMenuItem();
        mnuHangHoa = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenu();
        mnuHoaDonBan = new javax.swing.JMenuItem();
        mnuTimKiem = new javax.swing.JMenu();
        mnuTimHoaDon = new javax.swing.JMenuItem();
        mnuTimHang = new javax.swing.JMenuItem();
        mnuTimKhachHang = new javax.swing.JMenuItem();
        mnuBaoCao = new javax.swing.JMenu();
        mnuHangTon = new javax.swing.JMenuItem();
        mnuDoanhThu = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mnuHienTroGiup = new javax.swing.JMenuItem();
        mnuHoTro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Chương Trình Quản Lý ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Bán Quần Áo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        mnuTapTin.setText("File");

        mnuThoat.setText("Xóa");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnuTapTin.add(mnuThoat);

        jMenuBar1.add(mnuTapTin);

        mnuDanhMuc.setText("Danh Mục");

        mnuChatLieu.setText("Chất Liệu");
        mnuChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChatLieuActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuChatLieu);

        mnuNhanVien.setText("Nhân Viên");
        mnuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNhanVienActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuNhanVien);

        mnuKhachHang.setText("Khách Hàng");
        mnuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKhachHangActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuKhachHang);

        mnuHangHoa.setText("Hàng Hóa");
        mnuHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHangHoaActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuHangHoa);

        jMenuBar1.add(mnuDanhMuc);

        mnuHoaDon.setText("Hóa Đơn");

        mnuHoaDonBan.setText("Hóa Đơn Bán");
        mnuHoaDonBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHoaDonBanActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mnuHoaDonBan);

        jMenuBar1.add(mnuHoaDon);

        mnuTimKiem.setText("Tìm Kiếm");

        mnuTimHoaDon.setText("Tìm Hóa Đơn");
        mnuTimHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTimHoaDonActionPerformed(evt);
            }
        });
        mnuTimKiem.add(mnuTimHoaDon);

        mnuTimHang.setText("Tìm Hàng");
        mnuTimKiem.add(mnuTimHang);

        mnuTimKhachHang.setText("Tìm Khách Hàng");
        mnuTimKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTimKhachHangActionPerformed(evt);
            }
        });
        mnuTimKiem.add(mnuTimKhachHang);

        jMenuBar1.add(mnuTimKiem);

        mnuBaoCao.setText("Báo Cáo");

        mnuHangTon.setText("Hàng Tồn");
        mnuBaoCao.add(mnuHangTon);

        mnuDoanhThu.setText("Doanh Thu");
        mnuBaoCao.add(mnuDoanhThu);

        jMenuBar1.add(mnuBaoCao);

        mnuTroGiup.setText("Trợ Giúp");

        mnuHienTroGiup.setText("Hiện Trợ Giúp");
        mnuTroGiup.add(mnuHienTroGiup);

        mnuHoTro.setText("Hỗ Trợ");
        mnuTroGiup.add(mnuHoTro);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTimKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTimKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuTimKhachHangActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mnuChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChatLieuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new frmChatLieu().setVisible(true);
    }//GEN-LAST:event_mnuChatLieuActionPerformed

    private void mnuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNhanVienActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new frmNhanVien().setVisible(true);
    }//GEN-LAST:event_mnuNhanVienActionPerformed

    private void mnuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKhachHangActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new frmKhachHang().setVisible(true);
    }//GEN-LAST:event_mnuKhachHangActionPerformed

    private void mnuHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHangHoaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new frmHangHoa().setVisible(true);
    }//GEN-LAST:event_mnuHangHoaActionPerformed

    private void mnuHoaDonBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHoaDonBanActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new frmHoaDonBan().setVisible(true);
    }//GEN-LAST:event_mnuHoaDonBanActionPerformed

    private void mnuTimHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTimHoaDonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new frmTimKiemHD().setVisible(true);
    }//GEN-LAST:event_mnuTimHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuBaoCao;
    private javax.swing.JMenuItem mnuChatLieu;
    private javax.swing.JMenu mnuDanhMuc;
    private javax.swing.JMenuItem mnuDoanhThu;
    private javax.swing.JMenuItem mnuHangHoa;
    private javax.swing.JMenuItem mnuHangTon;
    private javax.swing.JMenuItem mnuHienTroGiup;
    private javax.swing.JMenuItem mnuHoTro;
    private javax.swing.JMenu mnuHoaDon;
    private javax.swing.JMenuItem mnuHoaDonBan;
    private javax.swing.JMenuItem mnuKhachHang;
    private javax.swing.JMenuItem mnuNhanVien;
    private javax.swing.JMenu mnuTapTin;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JMenuItem mnuTimHang;
    private javax.swing.JMenuItem mnuTimHoaDon;
    private javax.swing.JMenuItem mnuTimKhachHang;
    private javax.swing.JMenu mnuTimKiem;
    private javax.swing.JMenu mnuTroGiup;
    // End of variables declaration//GEN-END:variables

}
